version: 0.2
phases:
  build:
    commands:
      - pwd
      - ls
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Entered the post build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - target/aws-sdk.tar.gz
    - scripts/pre-deploy.sh
    - appspec.yml
  #discard-paths: yes
cache:
  paths:
    - '/ec2-user/.m2/**/*'
    - '/root/.m2/**/*'

